import { Inter } from "next/font/google";
import { AuthContextProvider } from '@/app/AuthContext'
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Tspin",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContextProvider>
          <div className="h-screen overlay w-full relative">
              {children}
          </div>
        </AuthContextProvider>
      </body>
    </html>
  );
}
